[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "audioread>=3.0.1",
    "librosa>=0.10.2.post1",
    "pydub>=0.25.1",
    "scipy>=1.14.1",
    "soundfile>=0.12.1",
]
